server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    #注册到zookeeper地址
    zookeeper:
      connect-string: 112.74.97.91:2181
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: cloud-provider-payment1 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8004   使用指定 ip 和 端口       #匹配后提供服务的路由地址
          uri: lb://cloud-provider-payment #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/zk        # 断言，路径相匹配的进行路由

        - id: cloud-provider-payment2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8004   使用指定 ip 和 端口       #匹配后提供服务的路由地址
          uri: lb://cloud-provider-payment #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/myLB         # 断言，路径相匹配的进行路由
            # - Host=**.comeOn.wang # 匹配域名
            # - Query=username, \d+
