server:
  port: 9004

spring:
  application:
    name: cloudAlibaba-sentinel-provide
  cloud:
    nacos:
      discovery:
        server-addr: 112.74.97.91:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
