server:
  port: 9101

spring:
  application:
    name: seata-account-server
  cloud:
    nacos:
      discovery:
        server-addr: 112.74.97.91:8848
    alibaba:
      seata:
        tx-service-group: default_tx_group
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://112.74.97.91:3306/seata_account
    username: root
    password: 12345

feign:
  hystrix:
    enabled: false

mybatis:
  mapperLocations: classpath:mapper/*.xml
