server:
  port: 8010

spring:
  application:
    name: cloud-stream-provider
  rabbitmq:
    host: 112.74.97.91
    port: 5672
    username: guest
    password: guest
  cloud:
    zookeeper:
      connect-string: 112.74.97.91:2181
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息；
        defaultRabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
      bindings: # 服务的整合处理
        output: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设置“text/plain”
