# 8009表示注册到zookeeper服务器的支付服务提供者端口号
server:
  port: 8009
#服务别名----注册zookeeper到注册中心名称
spring:
  application:
    name: cloud-providerHystrix-payment
  cloud:
    zookeeper:
      connect-string: 112.74.97.91:2181